name: Actions workflow
on: 
  push:
  schedule:
    - cron: "0/7 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    
jobs:
  run-github-actions:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: list files
        run: |
          pwd       
      - name: Simple Js Action  
        id: greets
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: me
      - name: log Greeting time
        run: echo "${{ steps.greets.outputs.time }}"
          
